import { getTag } from '../getTag';

const defaultWarnText = 'Do not edit this section in Markdown. Generated by code; change the source.';

export function getWarn(message?: string, opts?: {
  /** @default true */
  addNewLine?: boolean;
}): string {
  const addNewLine = opts?.addNewLine ?? true;
  return getTag('warn ' + (message ?? defaultWarnText), { addNewLine, style: 'open', type: 'meta' });
}