// May have whitespaces after tagXStart and tagEnd.
export const tagOpenerStart = '<!--\\$';
export const tagCloserStart = '<!--/\\$';
export const tagEnd = '-->';
/** E.g. <!--$ @typedoc-md --> */
export const pluginChar = '@';

export const warnTextDefault = '<!-- Do not edit this section in Markdown. Generated by code; change the source. -->';
export const sign = `<!--
  Markdown populated with mdol: https://github.com/SrBrahma/mdol.
  To repopulate it, run \`npx mdol\` in the project root.
-->`;

export const srcPath = __dirname;